server:
  gameWorldId: 1
  ip: 127.0.0.1
  serverPort: 10501
  # 工作线程数
  workerCount: 1
  # AOI视野距离(米)
  aoiViewArea: 50
  # 逻辑处理频率(hz)
  updateHz: 50
  # 心跳相关(单位：秒)
  heartBeatTimeOut: 30000
  heartBeatCheckInterval: 15
  heartBeatSendInterval: 10

cc:
  ip: 127.0.0.1
  port: 10100

database:
  host: 127.0.0.1
  port: 10200