// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Request;
@class Response;
@class UserLoginRequest;
@class UserLoginResponse;
@class UserRegisterRequest;
@class UserRegisterResponse;
@class Vector3;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MessageRoot : GPBRootObject
@end

#pragma mark - Vector3

typedef GPB_ENUM(Vector3_FieldNumber) {
  Vector3_FieldNumber_X = 1,
  Vector3_FieldNumber_Y = 2,
  Vector3_FieldNumber_Z = 3,
};

GPB_FINAL @interface Vector3 : GPBMessage

@property(nonatomic, readwrite) int32_t x;

@property(nonatomic, readwrite) int32_t y;

@property(nonatomic, readwrite) int32_t z;

@end

#pragma mark - Entity

typedef GPB_ENUM(Entity_FieldNumber) {
  Entity_FieldNumber_Id_p = 1,
  Entity_FieldNumber_Speed = 2,
  Entity_FieldNumber_Position = 3,
  Entity_FieldNumber_Rotation = 4,
};

GPB_FINAL @interface Entity : GPBMessage

@property(nonatomic, readwrite) int32_t id_p;

@property(nonatomic, readwrite) int32_t speed;

@property(nonatomic, readwrite, strong, null_resettable) Vector3 *position;
/** Test to see if @c position has been set. */
@property(nonatomic, readwrite) BOOL hasPosition;

@property(nonatomic, readwrite, strong, null_resettable) Vector3 *rotation;
/** Test to see if @c rotation has been set. */
@property(nonatomic, readwrite) BOOL hasRotation;

@end

#pragma mark - Package

typedef GPB_ENUM(Package_FieldNumber) {
  Package_FieldNumber_Request = 1,
  Package_FieldNumber_Response = 2,
};

GPB_FINAL @interface Package : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Request *request;
/** Test to see if @c request has been set. */
@property(nonatomic, readwrite) BOOL hasRequest;

@property(nonatomic, readwrite, strong, null_resettable) Response *response;
/** Test to see if @c response has been set. */
@property(nonatomic, readwrite) BOOL hasResponse;

@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_UserRegister = 1,
  Request_FieldNumber_UserLogin = 2,
};

GPB_FINAL @interface Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserRegisterRequest *userRegister;
/** Test to see if @c userRegister has been set. */
@property(nonatomic, readwrite) BOOL hasUserRegister;

@property(nonatomic, readwrite, strong, null_resettable) UserLoginRequest *userLogin;
/** Test to see if @c userLogin has been set. */
@property(nonatomic, readwrite) BOOL hasUserLogin;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_UserRegister = 1,
  Response_FieldNumber_UserLogin = 2,
};

GPB_FINAL @interface Response : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserRegisterResponse *userRegister;
/** Test to see if @c userRegister has been set. */
@property(nonatomic, readwrite) BOOL hasUserRegister;

@property(nonatomic, readwrite, strong, null_resettable) UserLoginResponse *userLogin;
/** Test to see if @c userLogin has been set. */
@property(nonatomic, readwrite) BOOL hasUserLogin;

@end

#pragma mark - UserRegisterRequest

typedef GPB_ENUM(UserRegisterRequest_FieldNumber) {
  UserRegisterRequest_FieldNumber_Username = 1,
  UserRegisterRequest_FieldNumber_Password = 2,
};

GPB_FINAL @interface UserRegisterRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - UserRegisterResponse

typedef GPB_ENUM(UserRegisterResponse_FieldNumber) {
  UserRegisterResponse_FieldNumber_Code = 1,
  UserRegisterResponse_FieldNumber_Message = 2,
};

GPB_FINAL @interface UserRegisterResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - UserLoginRequest

typedef GPB_ENUM(UserLoginRequest_FieldNumber) {
  UserLoginRequest_FieldNumber_Username = 1,
  UserLoginRequest_FieldNumber_Password = 2,
};

GPB_FINAL @interface UserLoginRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - UserLoginResponse

typedef GPB_ENUM(UserLoginResponse_FieldNumber) {
  UserLoginResponse_FieldNumber_Code = 1,
  UserLoginResponse_FieldNumber_Message = 2,
};

GPB_FINAL @interface UserLoginResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
