// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SceneEntity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HS.Protobuf.SceneEntity {

  /// <summary>Holder for reflection information generated from SceneEntity.proto</summary>
  public static partial class SceneEntityReflection {

    #region Descriptor
    /// <summary>File descriptor for SceneEntity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SceneEntityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTY2VuZUVudGl0eS5wcm90bxIXSFMuUHJvdG9idWYuU2NlbmVFbnRpdHka",
            "H0NvbW1vbi9Qcm90b1NvdXJjZS9Db21tb24ucHJvdG8aHkNvbWJhdC9Qcm90",
            "b1NvdXJjZS9Ta2lsbC5wcm90bxodQ29tYmF0L1Byb3RvU291cmNlL0J1ZmYu",
            "cHJvdG8aI0JhY2twYWNrL1Byb3RvU291cmNlL0JhY2twYWNrLnByb3RvInAK",
            "CU5ldEVudGl0eRIKCgJpZBgBIAEoBRIqCghwb3NpdGlvbhgCIAEoCzIYLkhT",
            "LlByb3RvYnVmLkNvbW1vbi5WZWMzEisKCWRpcmVjdGlvbhgDIAEoCzIYLkhT",
            "LlByb3RvYnVmLkNvbW1vbi5WZWMzIroDCghOZXRBY3RvchIKCgJpZBgBIAEo",
            "BRILCgN0aWQYAiABKAUSMgoGZW50aXR5GAMgASgLMiIuSFMuUHJvdG9idWYu",
            "U2NlbmVFbnRpdHkuTmV0RW50aXR5EgwKBG5hbWUYBCABKAkSDQoFbGV2ZWwY",
            "BSABKAUSCwoDZXhwGAYgASgDEg8KB3NwYWNlSWQYByABKAUSDAoEZ29sZBgI",
            "IAEoAxIKCgJocBgJIAEoAhIKCgJtcBgKIAEoAhI1CglhY3RvclR5cGUYCyAB",
            "KA4yIi5IUy5Qcm90b2J1Zi5TY2VuZUVudGl0eS5BY3RvclR5cGUSMwoGc2tp",
            "bGxzGAwgAygLMiMuSFMuUHJvdG9idWYuQ29tYmF0LlNraWxsLlNraWxsSW5m",
            "bxIxCgllcXVpcExpc3QYDSADKAsyHi5IUy5Qcm90b2J1Zi5CYWNrcGFjay5J",
            "dGVtSW5mbxINCgVocE1heBgOIAEoAhINCgVtcE1heBgPIAEoAhINCgVzcGVl",
            "ZBgQIAEoBRI0CglidWZmc0xpc3QYESADKAsyIS5IUy5Qcm90b2J1Zi5Db21i",
            "YXQuQnVmZi5CdWZmSW5mbyLzBAoOUHJvcGVydHlVcGRhdGUSEQoJZW50aXR5",
            "X2lkGAEgASgFEj4KCHByb3BlcnR5GAIgASgOMiwuSFMuUHJvdG9idWYuU2Nl",
            "bmVFbnRpdHkuUHJvcGVydHlVcGRhdGUuUHJvcBJHCghvbGRWYWx1ZRgDIAEo",
            "CzI1LkhTLlByb3RvYnVmLlNjZW5lRW50aXR5LlByb3BlcnR5VXBkYXRlLlBy",
            "b3BlcnR5VmFsdWUSRwoIbmV3VmFsdWUYBCABKAsyNS5IUy5Qcm90b2J1Zi5T",
            "Y2VuZUVudGl0eS5Qcm9wZXJ0eVVwZGF0ZS5Qcm9wZXJ0eVZhbHVlGvIBCg1Q",
            "cm9wZXJ0eVZhbHVlEhMKCWludF92YWx1ZRgBIAEoBUgAEhUKC2Zsb2F0X3Zh",
            "bHVlGAIgASgCSAASFgoMc3RyaW5nX3ZhbHVlGAMgASgJSAASOAoKbW9kZV92",
            "YWx1ZRgEIAEoDjIiLkhTLlByb3RvYnVmLlNjZW5lRW50aXR5LkFjdG9yTW9k",
            "ZUgAEhQKCmxvbmdfdmFsdWUYBSABKANIABJEChBjb21iYXRNb2RlX3ZhbHVl",
            "GAYgASgOMiguSFMuUHJvdG9idWYuU2NlbmVFbnRpdHkuQWN0b3JDb21iYXRN",
            "b2RlSABCBwoFdmFsdWUihgEKBFByb3ASBgoCSFAQABIGCgJNUBABEgkKBUhQ",
            "TWF4EAISCQoFTVBNYXgQAxIICgRNb2RlEAQSCQoFTGV2ZWwQBRIICgROYW1l",
            "EAYSCQoFR29sZHMQBxIHCgNFeHAQCBIKCgZFbmVyZ3kQCRIJCgVTcGVlZBAK",
            "Eg4KCkNvbWJhdE1vZGUQCyKBAQoITmV0RUl0ZW0SMAoISXRlbUluZm8YASAB",
            "KAsyHi5IUy5Qcm90b2J1Zi5CYWNrcGFjay5JdGVtSW5mbxIPCgdzcGFjZUlk",
            "GAIgASgFEjIKBmVudGl0eRgDIAEoCzIiLkhTLlByb3RvYnVmLlNjZW5lRW50",
            "aXR5Lk5ldEVudGl0eSo0CglBY3Rvck1vZGUSCAoERlJFRRAAEggKBERFQUQQ",
            "ARIICgRSRVNUEAISCQoFRklHSFQQAyo4Cg9BY3RvckNvbWJhdE1vZGUSCQoF",
            "U3RhbmQQABIJCgVFcXVpcBABEg8KC1N3b3JkRmxpZ2h0EAIqigEKCkFjdG9y",
            "U3RhdGUSCwoHQWlyRG93bhAAEgkKBURlYXRoEAESCwoHRGVmZW5zZRACEgkK",
            "BURpenp5EAMSCQoFRXZhZGUQBBIICgRIdXJ0EAUSCAoESWRsZRAGEgoKBkp1",
            "bXBVcBAHEggKBE1vdmUQCBIJCgVTa2lsbBAJEgwKCENvbnN0YW50EAoqMAoJ",
            "QWN0b3JUeXBlEg0KCUNoYXJhY3RlchAAEgsKB01vbnN0ZXIQARIHCgNOUEMQ",
            "AmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HS.Protobuf.Common.CommonReflection.Descriptor, global::HS.Protobuf.Combat.Skill.SkillReflection.Descriptor, global::HS.Protobuf.Combat.Buff.BuffReflection.Descriptor, global::HS.Protobuf.Backpack.BackpackReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HS.Protobuf.SceneEntity.ActorMode), typeof(global::HS.Protobuf.SceneEntity.ActorCombatMode), typeof(global::HS.Protobuf.SceneEntity.ActorState), typeof(global::HS.Protobuf.SceneEntity.ActorType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.SceneEntity.NetEntity), global::HS.Protobuf.SceneEntity.NetEntity.Parser, new[]{ "Id", "Position", "Direction" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.SceneEntity.NetActor), global::HS.Protobuf.SceneEntity.NetActor.Parser, new[]{ "Id", "Tid", "Entity", "Name", "Level", "Exp", "SpaceId", "Gold", "Hp", "Mp", "ActorType", "Skills", "EquipList", "HpMax", "MpMax", "Speed", "BuffsList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.SceneEntity.PropertyUpdate), global::HS.Protobuf.SceneEntity.PropertyUpdate.Parser, new[]{ "EntityId", "Property", "OldValue", "NewValue" }, null, new[]{ typeof(global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue), global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue.Parser, new[]{ "IntValue", "FloatValue", "StringValue", "ModeValue", "LongValue", "CombatModeValue" }, new[]{ "Value" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.SceneEntity.NetEItem), global::HS.Protobuf.SceneEntity.NetEItem.Parser, new[]{ "ItemInfo", "SpaceId", "Entity" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///活动单位的模式
  /// </summary>
  public enum ActorMode {
    /// <summary>
    ///自由进行任何操作
    /// </summary>
    [pbr::OriginalName("FREE")] Free = 0,
    /// <summary>
    ///死亡，无法操作。
    /// </summary>
    [pbr::OriginalName("DEAD")] Dead = 1,
    /// <summary>
    ///休息，挂机 回血回蓝(可以坐下的时候触发)
    /// </summary>
    [pbr::OriginalName("REST")] Rest = 2,
    /// <summary>
    ///战斗状态，持续一段时间，期间可能无法骑马吧。
    /// </summary>
    [pbr::OriginalName("FIGHT")] Fight = 3,
  }

  /// <summary>
  ///活动单位的行为
  /// </summary>
  public enum ActorCombatMode {
    [pbr::OriginalName("Stand")] Stand = 0,
    [pbr::OriginalName("Equip")] Equip = 1,
    [pbr::OriginalName("SwordFlight")] SwordFlight = 2,
  }

  public enum ActorState {
    [pbr::OriginalName("AirDown")] AirDown = 0,
    [pbr::OriginalName("Death")] Death = 1,
    [pbr::OriginalName("Defense")] Defense = 2,
    [pbr::OriginalName("Dizzy")] Dizzy = 3,
    [pbr::OriginalName("Evade")] Evade = 4,
    [pbr::OriginalName("Hurt")] Hurt = 5,
    [pbr::OriginalName("Idle")] Idle = 6,
    [pbr::OriginalName("JumpUp")] JumpUp = 7,
    [pbr::OriginalName("Move")] Move = 8,
    [pbr::OriginalName("Skill")] Skill = 9,
    [pbr::OriginalName("Constant")] Constant = 10,
  }

  /// <summary>
  ///actor类型
  /// </summary>
  public enum ActorType {
    [pbr::OriginalName("Character")] Character = 0,
    [pbr::OriginalName("Monster")] Monster = 1,
    [pbr::OriginalName("NPC")] Npc = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///entity位置信息
  /// </summary>
  public sealed partial class NetEntity : pb::IMessage<NetEntity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetEntity> _parser = new pb::MessageParser<NetEntity>(() => new NetEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.SceneEntity.SceneEntityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEntity(NetEntity other) : this() {
      id_ = other.id_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEntity Clone() {
      return new NetEntity(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::HS.Protobuf.Common.Vec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.Vec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 3;
    private global::HS.Protobuf.Common.Vec3 direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.Vec3 Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (direction_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Direction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (direction_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Direction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (direction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetEntity other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::HS.Protobuf.Common.Vec3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::HS.Protobuf.Common.Vec3();
        }
        Direction.MergeFrom(other.Direction);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::HS.Protobuf.Common.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            if (direction_ == null) {
              Direction = new global::HS.Protobuf.Common.Vec3();
            }
            input.ReadMessage(Direction);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::HS.Protobuf.Common.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            if (direction_ == null) {
              Direction = new global::HS.Protobuf.Common.Vec3();
            }
            input.ReadMessage(Direction);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///actor信息
  /// </summary>
  public sealed partial class NetActor : pb::IMessage<NetActor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetActor> _parser = new pb::MessageParser<NetActor>(() => new NetActor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetActor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.SceneEntity.SceneEntityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetActor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetActor(NetActor other) : this() {
      id_ = other.id_;
      tid_ = other.tid_;
      entity_ = other.entity_ != null ? other.entity_.Clone() : null;
      name_ = other.name_;
      level_ = other.level_;
      exp_ = other.exp_;
      spaceId_ = other.spaceId_;
      gold_ = other.gold_;
      hp_ = other.hp_;
      mp_ = other.mp_;
      actorType_ = other.actorType_;
      skills_ = other.skills_.Clone();
      equipList_ = other.equipList_.Clone();
      hpMax_ = other.hpMax_;
      mpMax_ = other.mpMax_;
      speed_ = other.speed_;
      buffsList_ = other.buffsList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetActor Clone() {
      return new NetActor(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "tid" field.</summary>
    public const int TidFieldNumber = 2;
    private int tid_;
    /// <summary>
    ///单位类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Tid {
      get { return tid_; }
      set {
        tid_ = value;
      }
    }

    /// <summary>Field number for the "entity" field.</summary>
    public const int EntityFieldNumber = 3;
    private global::HS.Protobuf.SceneEntity.NetEntity entity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.NetEntity Entity {
      get { return entity_; }
      set {
        entity_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 5;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 6;
    private long exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "spaceId" field.</summary>
    public const int SpaceIdFieldNumber = 7;
    private int spaceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpaceId {
      get { return spaceId_; }
      set {
        spaceId_ = value;
      }
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 8;
    private long gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 9;
    private float hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "mp" field.</summary>
    public const int MpFieldNumber = 10;
    private float mp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Mp {
      get { return mp_; }
      set {
        mp_ = value;
      }
    }

    /// <summary>Field number for the "actorType" field.</summary>
    public const int ActorTypeFieldNumber = 11;
    private global::HS.Protobuf.SceneEntity.ActorType actorType_ = global::HS.Protobuf.SceneEntity.ActorType.Character;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.ActorType ActorType {
      get { return actorType_; }
      set {
        actorType_ = value;
      }
    }

    /// <summary>Field number for the "skills" field.</summary>
    public const int SkillsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::HS.Protobuf.Combat.Skill.SkillInfo> _repeated_skills_codec
        = pb::FieldCodec.ForMessage(98, global::HS.Protobuf.Combat.Skill.SkillInfo.Parser);
    private readonly pbc::RepeatedField<global::HS.Protobuf.Combat.Skill.SkillInfo> skills_ = new pbc::RepeatedField<global::HS.Protobuf.Combat.Skill.SkillInfo>();
    /// <summary>
    ///技能列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HS.Protobuf.Combat.Skill.SkillInfo> Skills {
      get { return skills_; }
    }

    /// <summary>Field number for the "equipList" field.</summary>
    public const int EquipListFieldNumber = 13;
    private static readonly pb::FieldCodec<global::HS.Protobuf.Backpack.ItemInfo> _repeated_equipList_codec
        = pb::FieldCodec.ForMessage(106, global::HS.Protobuf.Backpack.ItemInfo.Parser);
    private readonly pbc::RepeatedField<global::HS.Protobuf.Backpack.ItemInfo> equipList_ = new pbc::RepeatedField<global::HS.Protobuf.Backpack.ItemInfo>();
    /// <summary>
    ///穿戴装备
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HS.Protobuf.Backpack.ItemInfo> EquipList {
      get { return equipList_; }
    }

    /// <summary>Field number for the "hpMax" field.</summary>
    public const int HpMaxFieldNumber = 14;
    private float hpMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float HpMax {
      get { return hpMax_; }
      set {
        hpMax_ = value;
      }
    }

    /// <summary>Field number for the "mpMax" field.</summary>
    public const int MpMaxFieldNumber = 15;
    private float mpMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MpMax {
      get { return mpMax_; }
      set {
        mpMax_ = value;
      }
    }

    /// <summary>Field number for the "speed" field.</summary>
    public const int SpeedFieldNumber = 16;
    private int speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "buffsList" field.</summary>
    public const int BuffsListFieldNumber = 17;
    private static readonly pb::FieldCodec<global::HS.Protobuf.Combat.Buff.BuffInfo> _repeated_buffsList_codec
        = pb::FieldCodec.ForMessage(138, global::HS.Protobuf.Combat.Buff.BuffInfo.Parser);
    private readonly pbc::RepeatedField<global::HS.Protobuf.Combat.Buff.BuffInfo> buffsList_ = new pbc::RepeatedField<global::HS.Protobuf.Combat.Buff.BuffInfo>();
    /// <summary>
    ///actor的buff
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HS.Protobuf.Combat.Buff.BuffInfo> BuffsList {
      get { return buffsList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetActor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetActor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Tid != other.Tid) return false;
      if (!object.Equals(Entity, other.Entity)) return false;
      if (Name != other.Name) return false;
      if (Level != other.Level) return false;
      if (Exp != other.Exp) return false;
      if (SpaceId != other.SpaceId) return false;
      if (Gold != other.Gold) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Hp, other.Hp)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Mp, other.Mp)) return false;
      if (ActorType != other.ActorType) return false;
      if(!skills_.Equals(other.skills_)) return false;
      if(!equipList_.Equals(other.equipList_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HpMax, other.HpMax)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MpMax, other.MpMax)) return false;
      if (Speed != other.Speed) return false;
      if(!buffsList_.Equals(other.buffsList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Tid != 0) hash ^= Tid.GetHashCode();
      if (entity_ != null) hash ^= Entity.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Exp != 0L) hash ^= Exp.GetHashCode();
      if (SpaceId != 0) hash ^= SpaceId.GetHashCode();
      if (Gold != 0L) hash ^= Gold.GetHashCode();
      if (Hp != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Hp);
      if (Mp != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Mp);
      if (ActorType != global::HS.Protobuf.SceneEntity.ActorType.Character) hash ^= ActorType.GetHashCode();
      hash ^= skills_.GetHashCode();
      hash ^= equipList_.GetHashCode();
      if (HpMax != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HpMax);
      if (MpMax != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MpMax);
      if (Speed != 0) hash ^= Speed.GetHashCode();
      hash ^= buffsList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Tid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Tid);
      }
      if (entity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Entity);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Level);
      }
      if (Exp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Exp);
      }
      if (SpaceId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SpaceId);
      }
      if (Gold != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Gold);
      }
      if (Hp != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(Hp);
      }
      if (Mp != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Mp);
      }
      if (ActorType != global::HS.Protobuf.SceneEntity.ActorType.Character) {
        output.WriteRawTag(88);
        output.WriteEnum((int) ActorType);
      }
      skills_.WriteTo(output, _repeated_skills_codec);
      equipList_.WriteTo(output, _repeated_equipList_codec);
      if (HpMax != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(HpMax);
      }
      if (MpMax != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(MpMax);
      }
      if (Speed != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Speed);
      }
      buffsList_.WriteTo(output, _repeated_buffsList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Tid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Tid);
      }
      if (entity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Entity);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Level);
      }
      if (Exp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Exp);
      }
      if (SpaceId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SpaceId);
      }
      if (Gold != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Gold);
      }
      if (Hp != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(Hp);
      }
      if (Mp != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(Mp);
      }
      if (ActorType != global::HS.Protobuf.SceneEntity.ActorType.Character) {
        output.WriteRawTag(88);
        output.WriteEnum((int) ActorType);
      }
      skills_.WriteTo(ref output, _repeated_skills_codec);
      equipList_.WriteTo(ref output, _repeated_equipList_codec);
      if (HpMax != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(HpMax);
      }
      if (MpMax != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(MpMax);
      }
      if (Speed != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Speed);
      }
      buffsList_.WriteTo(ref output, _repeated_buffsList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Tid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tid);
      }
      if (entity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entity);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Exp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      if (SpaceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpaceId);
      }
      if (Gold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      if (Hp != 0F) {
        size += 1 + 4;
      }
      if (Mp != 0F) {
        size += 1 + 4;
      }
      if (ActorType != global::HS.Protobuf.SceneEntity.ActorType.Character) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActorType);
      }
      size += skills_.CalculateSize(_repeated_skills_codec);
      size += equipList_.CalculateSize(_repeated_equipList_codec);
      if (HpMax != 0F) {
        size += 1 + 4;
      }
      if (MpMax != 0F) {
        size += 1 + 4;
      }
      if (Speed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Speed);
      }
      size += buffsList_.CalculateSize(_repeated_buffsList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetActor other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Tid != 0) {
        Tid = other.Tid;
      }
      if (other.entity_ != null) {
        if (entity_ == null) {
          Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
        }
        Entity.MergeFrom(other.Entity);
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Exp != 0L) {
        Exp = other.Exp;
      }
      if (other.SpaceId != 0) {
        SpaceId = other.SpaceId;
      }
      if (other.Gold != 0L) {
        Gold = other.Gold;
      }
      if (other.Hp != 0F) {
        Hp = other.Hp;
      }
      if (other.Mp != 0F) {
        Mp = other.Mp;
      }
      if (other.ActorType != global::HS.Protobuf.SceneEntity.ActorType.Character) {
        ActorType = other.ActorType;
      }
      skills_.Add(other.skills_);
      equipList_.Add(other.equipList_);
      if (other.HpMax != 0F) {
        HpMax = other.HpMax;
      }
      if (other.MpMax != 0F) {
        MpMax = other.MpMax;
      }
      if (other.Speed != 0) {
        Speed = other.Speed;
      }
      buffsList_.Add(other.buffsList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Tid = input.ReadInt32();
            break;
          }
          case 26: {
            if (entity_ == null) {
              Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
            }
            input.ReadMessage(Entity);
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Level = input.ReadInt32();
            break;
          }
          case 48: {
            Exp = input.ReadInt64();
            break;
          }
          case 56: {
            SpaceId = input.ReadInt32();
            break;
          }
          case 64: {
            Gold = input.ReadInt64();
            break;
          }
          case 77: {
            Hp = input.ReadFloat();
            break;
          }
          case 85: {
            Mp = input.ReadFloat();
            break;
          }
          case 88: {
            ActorType = (global::HS.Protobuf.SceneEntity.ActorType) input.ReadEnum();
            break;
          }
          case 98: {
            skills_.AddEntriesFrom(input, _repeated_skills_codec);
            break;
          }
          case 106: {
            equipList_.AddEntriesFrom(input, _repeated_equipList_codec);
            break;
          }
          case 117: {
            HpMax = input.ReadFloat();
            break;
          }
          case 125: {
            MpMax = input.ReadFloat();
            break;
          }
          case 128: {
            Speed = input.ReadInt32();
            break;
          }
          case 138: {
            buffsList_.AddEntriesFrom(input, _repeated_buffsList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Tid = input.ReadInt32();
            break;
          }
          case 26: {
            if (entity_ == null) {
              Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
            }
            input.ReadMessage(Entity);
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Level = input.ReadInt32();
            break;
          }
          case 48: {
            Exp = input.ReadInt64();
            break;
          }
          case 56: {
            SpaceId = input.ReadInt32();
            break;
          }
          case 64: {
            Gold = input.ReadInt64();
            break;
          }
          case 77: {
            Hp = input.ReadFloat();
            break;
          }
          case 85: {
            Mp = input.ReadFloat();
            break;
          }
          case 88: {
            ActorType = (global::HS.Protobuf.SceneEntity.ActorType) input.ReadEnum();
            break;
          }
          case 98: {
            skills_.AddEntriesFrom(ref input, _repeated_skills_codec);
            break;
          }
          case 106: {
            equipList_.AddEntriesFrom(ref input, _repeated_equipList_codec);
            break;
          }
          case 117: {
            HpMax = input.ReadFloat();
            break;
          }
          case 125: {
            MpMax = input.ReadFloat();
            break;
          }
          case 128: {
            Speed = input.ReadInt32();
            break;
          }
          case 138: {
            buffsList_.AddEntriesFrom(ref input, _repeated_buffsList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///actor属性更新消息类型
  /// </summary>
  public sealed partial class PropertyUpdate : pb::IMessage<PropertyUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PropertyUpdate> _parser = new pb::MessageParser<PropertyUpdate>(() => new PropertyUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PropertyUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.SceneEntity.SceneEntityReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropertyUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropertyUpdate(PropertyUpdate other) : this() {
      entityId_ = other.entityId_;
      property_ = other.property_;
      oldValue_ = other.oldValue_ != null ? other.oldValue_.Clone() : null;
      newValue_ = other.newValue_ != null ? other.newValue_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PropertyUpdate Clone() {
      return new PropertyUpdate(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private int entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "property" field.</summary>
    public const int PropertyFieldNumber = 2;
    private global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop property_ = global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop Property {
      get { return property_; }
      set {
        property_ = value;
      }
    }

    /// <summary>Field number for the "oldValue" field.</summary>
    public const int OldValueFieldNumber = 3;
    private global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue oldValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue OldValue {
      get { return oldValue_; }
      set {
        oldValue_ = value;
      }
    }

    /// <summary>Field number for the "newValue" field.</summary>
    public const int NewValueFieldNumber = 4;
    private global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue newValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue NewValue {
      get { return newValue_; }
      set {
        newValue_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PropertyUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PropertyUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (Property != other.Property) return false;
      if (!object.Equals(OldValue, other.OldValue)) return false;
      if (!object.Equals(NewValue, other.NewValue)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (Property != global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp) hash ^= Property.GetHashCode();
      if (oldValue_ != null) hash ^= OldValue.GetHashCode();
      if (newValue_ != null) hash ^= NewValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EntityId);
      }
      if (Property != global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Property);
      }
      if (oldValue_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OldValue);
      }
      if (newValue_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(NewValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EntityId);
      }
      if (Property != global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Property);
      }
      if (oldValue_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OldValue);
      }
      if (newValue_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(NewValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
      }
      if (Property != global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Property);
      }
      if (oldValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OldValue);
      }
      if (newValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PropertyUpdate other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.Property != global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop.Hp) {
        Property = other.Property;
      }
      if (other.oldValue_ != null) {
        if (oldValue_ == null) {
          OldValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
        }
        OldValue.MergeFrom(other.OldValue);
      }
      if (other.newValue_ != null) {
        if (newValue_ == null) {
          NewValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
        }
        NewValue.MergeFrom(other.NewValue);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EntityId = input.ReadInt32();
            break;
          }
          case 16: {
            Property = (global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop) input.ReadEnum();
            break;
          }
          case 26: {
            if (oldValue_ == null) {
              OldValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
            }
            input.ReadMessage(OldValue);
            break;
          }
          case 34: {
            if (newValue_ == null) {
              NewValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
            }
            input.ReadMessage(NewValue);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EntityId = input.ReadInt32();
            break;
          }
          case 16: {
            Property = (global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.Prop) input.ReadEnum();
            break;
          }
          case 26: {
            if (oldValue_ == null) {
              OldValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
            }
            input.ReadMessage(OldValue);
            break;
          }
          case 34: {
            if (newValue_ == null) {
              NewValue = new global::HS.Protobuf.SceneEntity.PropertyUpdate.Types.PropertyValue();
            }
            input.ReadMessage(NewValue);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PropertyUpdate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///属性类型枚举
      /// </summary>
      public enum Prop {
        [pbr::OriginalName("HP")] Hp = 0,
        [pbr::OriginalName("MP")] Mp = 1,
        [pbr::OriginalName("HPMax")] Hpmax = 2,
        [pbr::OriginalName("MPMax")] Mpmax = 3,
        [pbr::OriginalName("Mode")] Mode = 4,
        [pbr::OriginalName("Level")] Level = 5,
        [pbr::OriginalName("Name")] Name = 6,
        [pbr::OriginalName("Golds")] Golds = 7,
        /// <summary>
        ///经验
        /// </summary>
        [pbr::OriginalName("Exp")] Exp = 8,
        /// <summary>
        ///活力
        /// </summary>
        [pbr::OriginalName("Energy")] Energy = 9,
        [pbr::OriginalName("Speed")] Speed = 10,
        [pbr::OriginalName("CombatMode")] CombatMode = 11,
      }

      /// <summary>
      ///为了可以存放不同的类型的数据
      /// </summary>
      public sealed partial class PropertyValue : pb::IMessage<PropertyValue>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<PropertyValue> _parser = new pb::MessageParser<PropertyValue>(() => new PropertyValue());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PropertyValue> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::HS.Protobuf.SceneEntity.PropertyUpdate.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PropertyValue() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PropertyValue(PropertyValue other) : this() {
          switch (other.ValueCase) {
            case ValueOneofCase.IntValue:
              IntValue = other.IntValue;
              break;
            case ValueOneofCase.FloatValue:
              FloatValue = other.FloatValue;
              break;
            case ValueOneofCase.StringValue:
              StringValue = other.StringValue;
              break;
            case ValueOneofCase.ModeValue:
              ModeValue = other.ModeValue;
              break;
            case ValueOneofCase.LongValue:
              LongValue = other.LongValue;
              break;
            case ValueOneofCase.CombatModeValue:
              CombatModeValue = other.CombatModeValue;
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PropertyValue Clone() {
          return new PropertyValue(this);
        }

        /// <summary>Field number for the "int_value" field.</summary>
        public const int IntValueFieldNumber = 1;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int IntValue {
          get { return valueCase_ == ValueOneofCase.IntValue ? (int) value_ : 0; }
          set {
            value_ = value;
            valueCase_ = ValueOneofCase.IntValue;
          }
        }

        /// <summary>Field number for the "float_value" field.</summary>
        public const int FloatValueFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float FloatValue {
          get { return valueCase_ == ValueOneofCase.FloatValue ? (float) value_ : 0F; }
          set {
            value_ = value;
            valueCase_ = ValueOneofCase.FloatValue;
          }
        }

        /// <summary>Field number for the "string_value" field.</summary>
        public const int StringValueFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string StringValue {
          get { return valueCase_ == ValueOneofCase.StringValue ? (string) value_ : ""; }
          set {
            value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            valueCase_ = ValueOneofCase.StringValue;
          }
        }

        /// <summary>Field number for the "mode_value" field.</summary>
        public const int ModeValueFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::HS.Protobuf.SceneEntity.ActorMode ModeValue {
          get { return valueCase_ == ValueOneofCase.ModeValue ? (global::HS.Protobuf.SceneEntity.ActorMode) value_ : global::HS.Protobuf.SceneEntity.ActorMode.Free; }
          set {
            value_ = value;
            valueCase_ = ValueOneofCase.ModeValue;
          }
        }

        /// <summary>Field number for the "long_value" field.</summary>
        public const int LongValueFieldNumber = 5;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long LongValue {
          get { return valueCase_ == ValueOneofCase.LongValue ? (long) value_ : 0L; }
          set {
            value_ = value;
            valueCase_ = ValueOneofCase.LongValue;
          }
        }

        /// <summary>Field number for the "combatMode_value" field.</summary>
        public const int CombatModeValueFieldNumber = 6;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::HS.Protobuf.SceneEntity.ActorCombatMode CombatModeValue {
          get { return valueCase_ == ValueOneofCase.CombatModeValue ? (global::HS.Protobuf.SceneEntity.ActorCombatMode) value_ : global::HS.Protobuf.SceneEntity.ActorCombatMode.Stand; }
          set {
            value_ = value;
            valueCase_ = ValueOneofCase.CombatModeValue;
          }
        }

        private object value_;
        /// <summary>Enum of possible cases for the "value" oneof.</summary>
        public enum ValueOneofCase {
          None = 0,
          IntValue = 1,
          FloatValue = 2,
          StringValue = 3,
          ModeValue = 4,
          LongValue = 5,
          CombatModeValue = 6,
        }
        private ValueOneofCase valueCase_ = ValueOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ValueOneofCase ValueCase {
          get { return valueCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearValue() {
          valueCase_ = ValueOneofCase.None;
          value_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as PropertyValue);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PropertyValue other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (IntValue != other.IntValue) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
          if (StringValue != other.StringValue) return false;
          if (ModeValue != other.ModeValue) return false;
          if (LongValue != other.LongValue) return false;
          if (CombatModeValue != other.CombatModeValue) return false;
          if (ValueCase != other.ValueCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (valueCase_ == ValueOneofCase.IntValue) hash ^= IntValue.GetHashCode();
          if (valueCase_ == ValueOneofCase.FloatValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue);
          if (valueCase_ == ValueOneofCase.StringValue) hash ^= StringValue.GetHashCode();
          if (valueCase_ == ValueOneofCase.ModeValue) hash ^= ModeValue.GetHashCode();
          if (valueCase_ == ValueOneofCase.LongValue) hash ^= LongValue.GetHashCode();
          if (valueCase_ == ValueOneofCase.CombatModeValue) hash ^= CombatModeValue.GetHashCode();
          hash ^= (int) valueCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (valueCase_ == ValueOneofCase.IntValue) {
            output.WriteRawTag(8);
            output.WriteInt32(IntValue);
          }
          if (valueCase_ == ValueOneofCase.FloatValue) {
            output.WriteRawTag(21);
            output.WriteFloat(FloatValue);
          }
          if (valueCase_ == ValueOneofCase.StringValue) {
            output.WriteRawTag(26);
            output.WriteString(StringValue);
          }
          if (valueCase_ == ValueOneofCase.ModeValue) {
            output.WriteRawTag(32);
            output.WriteEnum((int) ModeValue);
          }
          if (valueCase_ == ValueOneofCase.LongValue) {
            output.WriteRawTag(40);
            output.WriteInt64(LongValue);
          }
          if (valueCase_ == ValueOneofCase.CombatModeValue) {
            output.WriteRawTag(48);
            output.WriteEnum((int) CombatModeValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (valueCase_ == ValueOneofCase.IntValue) {
            output.WriteRawTag(8);
            output.WriteInt32(IntValue);
          }
          if (valueCase_ == ValueOneofCase.FloatValue) {
            output.WriteRawTag(21);
            output.WriteFloat(FloatValue);
          }
          if (valueCase_ == ValueOneofCase.StringValue) {
            output.WriteRawTag(26);
            output.WriteString(StringValue);
          }
          if (valueCase_ == ValueOneofCase.ModeValue) {
            output.WriteRawTag(32);
            output.WriteEnum((int) ModeValue);
          }
          if (valueCase_ == ValueOneofCase.LongValue) {
            output.WriteRawTag(40);
            output.WriteInt64(LongValue);
          }
          if (valueCase_ == ValueOneofCase.CombatModeValue) {
            output.WriteRawTag(48);
            output.WriteEnum((int) CombatModeValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (valueCase_ == ValueOneofCase.IntValue) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntValue);
          }
          if (valueCase_ == ValueOneofCase.FloatValue) {
            size += 1 + 4;
          }
          if (valueCase_ == ValueOneofCase.StringValue) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
          }
          if (valueCase_ == ValueOneofCase.ModeValue) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ModeValue);
          }
          if (valueCase_ == ValueOneofCase.LongValue) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(LongValue);
          }
          if (valueCase_ == ValueOneofCase.CombatModeValue) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CombatModeValue);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PropertyValue other) {
          if (other == null) {
            return;
          }
          switch (other.ValueCase) {
            case ValueOneofCase.IntValue:
              IntValue = other.IntValue;
              break;
            case ValueOneofCase.FloatValue:
              FloatValue = other.FloatValue;
              break;
            case ValueOneofCase.StringValue:
              StringValue = other.StringValue;
              break;
            case ValueOneofCase.ModeValue:
              ModeValue = other.ModeValue;
              break;
            case ValueOneofCase.LongValue:
              LongValue = other.LongValue;
              break;
            case ValueOneofCase.CombatModeValue:
              CombatModeValue = other.CombatModeValue;
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                IntValue = input.ReadInt32();
                break;
              }
              case 21: {
                FloatValue = input.ReadFloat();
                break;
              }
              case 26: {
                StringValue = input.ReadString();
                break;
              }
              case 32: {
                value_ = input.ReadEnum();
                valueCase_ = ValueOneofCase.ModeValue;
                break;
              }
              case 40: {
                LongValue = input.ReadInt64();
                break;
              }
              case 48: {
                value_ = input.ReadEnum();
                valueCase_ = ValueOneofCase.CombatModeValue;
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                IntValue = input.ReadInt32();
                break;
              }
              case 21: {
                FloatValue = input.ReadFloat();
                break;
              }
              case 26: {
                StringValue = input.ReadString();
                break;
              }
              case 32: {
                value_ = input.ReadEnum();
                valueCase_ = ValueOneofCase.ModeValue;
                break;
              }
              case 40: {
                LongValue = input.ReadInt64();
                break;
              }
              case 48: {
                value_ = input.ReadEnum();
                valueCase_ = ValueOneofCase.CombatModeValue;
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// Net itemEntity信息
  /// </summary>
  public sealed partial class NetEItem : pb::IMessage<NetEItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetEItem> _parser = new pb::MessageParser<NetEItem>(() => new NetEItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetEItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.SceneEntity.SceneEntityReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEItem(NetEItem other) : this() {
      itemInfo_ = other.itemInfo_ != null ? other.itemInfo_.Clone() : null;
      spaceId_ = other.spaceId_;
      entity_ = other.entity_ != null ? other.entity_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetEItem Clone() {
      return new NetEItem(this);
    }

    /// <summary>Field number for the "ItemInfo" field.</summary>
    public const int ItemInfoFieldNumber = 1;
    private global::HS.Protobuf.Backpack.ItemInfo itemInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Backpack.ItemInfo ItemInfo {
      get { return itemInfo_; }
      set {
        itemInfo_ = value;
      }
    }

    /// <summary>Field number for the "spaceId" field.</summary>
    public const int SpaceIdFieldNumber = 2;
    private int spaceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpaceId {
      get { return spaceId_; }
      set {
        spaceId_ = value;
      }
    }

    /// <summary>Field number for the "entity" field.</summary>
    public const int EntityFieldNumber = 3;
    private global::HS.Protobuf.SceneEntity.NetEntity entity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.SceneEntity.NetEntity Entity {
      get { return entity_; }
      set {
        entity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetEItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetEItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ItemInfo, other.ItemInfo)) return false;
      if (SpaceId != other.SpaceId) return false;
      if (!object.Equals(Entity, other.Entity)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (itemInfo_ != null) hash ^= ItemInfo.GetHashCode();
      if (SpaceId != 0) hash ^= SpaceId.GetHashCode();
      if (entity_ != null) hash ^= Entity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (itemInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemInfo);
      }
      if (SpaceId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SpaceId);
      }
      if (entity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Entity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (itemInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemInfo);
      }
      if (SpaceId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SpaceId);
      }
      if (entity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Entity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (itemInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemInfo);
      }
      if (SpaceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpaceId);
      }
      if (entity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetEItem other) {
      if (other == null) {
        return;
      }
      if (other.itemInfo_ != null) {
        if (itemInfo_ == null) {
          ItemInfo = new global::HS.Protobuf.Backpack.ItemInfo();
        }
        ItemInfo.MergeFrom(other.ItemInfo);
      }
      if (other.SpaceId != 0) {
        SpaceId = other.SpaceId;
      }
      if (other.entity_ != null) {
        if (entity_ == null) {
          Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
        }
        Entity.MergeFrom(other.Entity);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (itemInfo_ == null) {
              ItemInfo = new global::HS.Protobuf.Backpack.ItemInfo();
            }
            input.ReadMessage(ItemInfo);
            break;
          }
          case 16: {
            SpaceId = input.ReadInt32();
            break;
          }
          case 26: {
            if (entity_ == null) {
              Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
            }
            input.ReadMessage(Entity);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (itemInfo_ == null) {
              ItemInfo = new global::HS.Protobuf.Backpack.ItemInfo();
            }
            input.ReadMessage(ItemInfo);
            break;
          }
          case 16: {
            SpaceId = input.ReadInt32();
            break;
          }
          case 26: {
            if (entity_ == null) {
              Entity = new global::HS.Protobuf.SceneEntity.NetEntity();
            }
            input.ReadMessage(Entity);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
