server:
  ip: 127.0.0.1
  port: 10200
  # 工作线程数
  workerCount: 1
  # 逻辑处理频率(hz)
  updateHz: 50
  # 心跳相关(单位：秒)
  heartBeatTimeOut: 30000
  heartBeatCheckInterval: 15
  heartBeatSendInterval: 10

mongodb:
  connectionString: mongodb://localhost:27018
  databaseName: mmorpg


cc:
  ip: 127.0.0.1
  port: 10100