// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DBInventory .proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HS.Protobuf.DBProxy.DBInventory {

  /// <summary>Holder for reflection information generated from DBInventory .proto</summary>
  public static partial class DBInventoryReflection {

    #region Descriptor
    /// <summary>File descriptor for DBInventory .proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DBInventoryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJEQkludmVudG9yeSAucHJvdG8SH0hTLlByb3RvYnVmLkRCUHJveHkuREJJ",
            "bnZlbnRvcnkqMwoTREJJbnZlbnRvcnlQcm90b2NvbBIcChhEQklOVkVOVE9S",
            "WV9QUk9UT0NMX05PTkUQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HS.Protobuf.DBProxy.DBInventory.DBInventoryProtocol), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum DBInventoryProtocol {
    [pbr::OriginalName("DBINVENTORY_PROTOCL_NONE")] DbinventoryProtoclNone = 0,
  }

  #endregion

}

#endregion Designer generated code
