database:
  ip: 127.0.0.1
  port: 3306

server:
  ip: 127.0.0.1
  port: 10800
  # 工作线程数
  workerCount: 1
  # 逻辑处理频率(hz)
  updateHz: 50
  # 心跳相关(单位：秒)
  heartBeatTimeOut: 30
  heartBeatCheckInterval: 15
  heartBeatSendInterval: 10

cc:
  ip: 127.0.0.1
  port: 10100