// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameGateMgr.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HS.Protobuf.GameGateMgr {

  /// <summary>Holder for reflection information generated from GameGateMgr.proto</summary>
  public static partial class GameGateMgrReflection {

    #region Descriptor
    /// <summary>File descriptor for GameGateMgr.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameGateMgrReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHYW1lR2F0ZU1nci5wcm90bxIXSFMuUHJvdG9idWYuR2FtZUdhdGVNZ3Ia",
            "H0NvbW1vbi9Qcm90b1NvdXJjZS9Db21tb24ucHJvdG8iUgoUUmVnaXN0ZXJU",
            "b0dHTVJlcXVlc3QSOgoOc2VydmVySW5mb05vZGUYASABKAsyIi5IUy5Qcm90",
            "b2J1Zi5Db21tb24uU2VydmVySW5mb05vZGUiPgoVUmVnaXN0ZXJUb0dHTVJl",
            "c3BvbnNlEhIKCnJlc3VsdENvZGUYASABKAUSEQoJcmVzdWx0TXNnGAIgASgJ",
            "IsMBChdFeGVjdXRlR0dDb21tYW5kUmVxdWVzdBIwCgdjb21tYW5kGAEgASgO",
            "Mh8uSFMuUHJvdG9idWYuQ29tbW9uLkdhdGVDb21tYW5kEhYKDnRhcmdldFNl",
            "cnZlcklkGAIgASgFEhEKCXRpbWVTdGFtcBgDIAEoAxJAChJnYW1lU2VydmVy",
            "SW5mb05vZGUYBCABKAsyIi5IUy5Qcm90b2J1Zi5Db21tb24uU2VydmVySW5m",
            "b05vZGVIAEIJCgdwYXlsb2FkImMKGEV4ZWN1dGVHR0NvbW1hbmRSZXNwb25z",
            "ZRISCgpyZXN1bHRDb2RlGAEgASgFEjMKCmVyckNvbW1hbmQYAiABKA4yHy5I",
            "Uy5Qcm90b2J1Zi5Db21tb24uR2F0ZUNvbW1hbmQiwgEKFkV4ZWN1dGVTQ29t",
            "bWFuZFJlcXVlc3QSMAoHY29tbWFuZBgBIAEoDjIfLkhTLlByb3RvYnVmLkNv",
            "bW1vbi5HYXRlQ29tbWFuZBIWCg50YXJnZXRTZXJ2ZXJJZBgCIAEoBRIRCgl0",
            "aW1lU3RhbXAYAyABKAMSQAoSZ2FtZVNlcnZlckluZm9Ob2RlGAQgASgLMiIu",
            "SFMuUHJvdG9idWYuQ29tbW9uLlNlcnZlckluZm9Ob2RlSABCCQoHcGF5bG9h",
            "ZCJiChdFeGVjdXRlU0NvbW1hbmRSZXNwb25zZRISCgpyZXN1bHRDb2RlGAEg",
            "ASgFEjMKCmVyckNvbW1hbmQYAiABKA4yHy5IUy5Qcm90b2J1Zi5Db21tb24u",
            "R2F0ZUNvbW1hbmQiXgobUmVnaXN0ZXJTZXNzaW9uVG9HR01SZXF1ZXN0Eg4K",
            "BnRhc2tJZBgBIAEoBRIPCgd3b3JsZElkGAIgASgFEhEKCXNlc3Npb25JZBgD",
            "IAEoCRILCgN1SWQYBCABKAkikAEKHFJlZ2lzdGVyU2Vzc2lvblRvR0dNUmVz",
            "cG9uc2USDgoGdGFza0lkGAEgASgFEhIKCnJlc3VsdENvZGUYAiABKAUSEQoJ",
            "cmVzdWx0TXNnGAMgASgJEjkKDWdhbWVHYXRlSW5mb3MYBCADKAsyIi5IUy5Q",
            "cm90b2J1Zi5Db21tb24uU2VydmVySW5mb05vZGUqygMKEkdhbWVHYXRlTWdy",
            "UHJvdG9jbBIcChhHQU1FR0FURU1HUl9QUk9UT0NMX05PTkUQABItCidHQU1F",
            "R0FURU1HUl9QUk9UT0NMX1JFR0lTVEVSX1RPX0dHTV9SRVEQgfoBEi4KKEdB",
            "TUVHQVRFTUdSX1BST1RPQ0xfUkVHSVNURVJfVE9fR0dNX1JFU1AQgvoBEjAK",
            "KkdBTUVHQVRFTUdSX1BST1RPQ0xfRVhFQ1VURV9HR19DT01NQU5EX1JFURCD",
            "+gESMQorR0FNRUdBVEVNR1JfUFJPVE9DTF9FWEVDVVRFX0dHX0NPTU1BTkRf",
            "UkVTUBCE+gESLwopR0FNRUdBVEVNR1JfUFJPVE9DTF9FWEVDVVRFX1NfQ09N",
            "TUFORF9SRVEQhfoBEjAKKkdBTUVHQVRFTUdSX1BST1RPQ0xfRVhFQ1VURV9T",
            "X0NPTU1BTkRfUkVTUBCG+gESNgowR0FNRUdBVEVNR1JfUFJPVE9DTF9SRUdJ",
            "U1RFUl9TRVNTT0lPTl9UT19HR01fUkVREIf6ARI3CjFHQU1FR0FURU1HUl9Q",
            "Uk9UT0NMX1JFR0lTVEVSX1NFU1NPSU9OX1RPX0dHTV9SRVNQEIj6AWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::HS.Protobuf.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HS.Protobuf.GameGateMgr.GameGateMgrProtocl), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.RegisterToGGMRequest), global::HS.Protobuf.GameGateMgr.RegisterToGGMRequest.Parser, new[]{ "ServerInfoNode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.RegisterToGGMResponse), global::HS.Protobuf.GameGateMgr.RegisterToGGMResponse.Parser, new[]{ "ResultCode", "ResultMsg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.ExecuteGGCommandRequest), global::HS.Protobuf.GameGateMgr.ExecuteGGCommandRequest.Parser, new[]{ "Command", "TargetServerId", "TimeStamp", "GameServerInfoNode" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.ExecuteGGCommandResponse), global::HS.Protobuf.GameGateMgr.ExecuteGGCommandResponse.Parser, new[]{ "ResultCode", "ErrCommand" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.ExecuteSCommandRequest), global::HS.Protobuf.GameGateMgr.ExecuteSCommandRequest.Parser, new[]{ "Command", "TargetServerId", "TimeStamp", "GameServerInfoNode" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.ExecuteSCommandResponse), global::HS.Protobuf.GameGateMgr.ExecuteSCommandResponse.Parser, new[]{ "ResultCode", "ErrCommand" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.RegisterSessionToGGMRequest), global::HS.Protobuf.GameGateMgr.RegisterSessionToGGMRequest.Parser, new[]{ "TaskId", "WorldId", "SessionId", "UId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HS.Protobuf.GameGateMgr.RegisterSessionToGGMResponse), global::HS.Protobuf.GameGateMgr.RegisterSessionToGGMResponse.Parser, new[]{ "TaskId", "ResultCode", "ResultMsg", "GameGateInfos" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameGateMgrProtocl {
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_NONE")] None = 0,
    /// <summary>
    ///[RegisterToGGMRequest]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_REGISTER_TO_GGM_REQ")] RegisterToGgmReq = 32001,
    /// <summary>
    ///[RegisterToGGMResponse]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_REGISTER_TO_GGM_RESP")] RegisterToGgmResp = 32002,
    /// <summary>
    ///[ExecuteGGCommandRequest]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_EXECUTE_GG_COMMAND_REQ")] ExecuteGgCommandReq = 32003,
    /// <summary>
    ///[ExecuteGGCommandResponse]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_EXECUTE_GG_COMMAND_RESP")] ExecuteGgCommandResp = 32004,
    /// <summary>
    ///[ExecuteSCommandRequest]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_EXECUTE_S_COMMAND_REQ")] ExecuteSCommandReq = 32005,
    /// <summary>
    ///[ExecuteSCommandResponse]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_EXECUTE_S_COMMAND_RESP")] ExecuteSCommandResp = 32006,
    /// <summary>
    ///[RegisterSessionToGGMRequest]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_REGISTER_SESSOION_TO_GGM_REQ")] RegisterSessoionToGgmReq = 32007,
    /// <summary>
    ///[RegisterSessionToGGMResponse]
    /// </summary>
    [pbr::OriginalName("GAMEGATEMGR_PROTOCL_REGISTER_SESSOION_TO_GGM_RESP")] RegisterSessoionToGgmResp = 32008,
  }

  #endregion

  #region Messages
  public sealed partial class RegisterToGGMRequest : pb::IMessage<RegisterToGGMRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterToGGMRequest> _parser = new pb::MessageParser<RegisterToGGMRequest>(() => new RegisterToGGMRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterToGGMRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMRequest(RegisterToGGMRequest other) : this() {
      serverInfoNode_ = other.serverInfoNode_ != null ? other.serverInfoNode_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMRequest Clone() {
      return new RegisterToGGMRequest(this);
    }

    /// <summary>Field number for the "serverInfoNode" field.</summary>
    public const int ServerInfoNodeFieldNumber = 1;
    private global::HS.Protobuf.Common.ServerInfoNode serverInfoNode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.ServerInfoNode ServerInfoNode {
      get { return serverInfoNode_; }
      set {
        serverInfoNode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterToGGMRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterToGGMRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ServerInfoNode, other.ServerInfoNode)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (serverInfoNode_ != null) hash ^= ServerInfoNode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (serverInfoNode_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (serverInfoNode_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (serverInfoNode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerInfoNode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterToGGMRequest other) {
      if (other == null) {
        return;
      }
      if (other.serverInfoNode_ != null) {
        if (serverInfoNode_ == null) {
          ServerInfoNode = new global::HS.Protobuf.Common.ServerInfoNode();
        }
        ServerInfoNode.MergeFrom(other.ServerInfoNode);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (serverInfoNode_ == null) {
              ServerInfoNode = new global::HS.Protobuf.Common.ServerInfoNode();
            }
            input.ReadMessage(ServerInfoNode);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (serverInfoNode_ == null) {
              ServerInfoNode = new global::HS.Protobuf.Common.ServerInfoNode();
            }
            input.ReadMessage(ServerInfoNode);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RegisterToGGMResponse : pb::IMessage<RegisterToGGMResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterToGGMResponse> _parser = new pb::MessageParser<RegisterToGGMResponse>(() => new RegisterToGGMResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterToGGMResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMResponse(RegisterToGGMResponse other) : this() {
      resultCode_ = other.resultCode_;
      resultMsg_ = other.resultMsg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterToGGMResponse Clone() {
      return new RegisterToGGMResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    /// <summary>
    ///0 成功 小于0正常流程  大于0异常流程
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "resultMsg" field.</summary>
    public const int ResultMsgFieldNumber = 2;
    private string resultMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResultMsg {
      get { return resultMsg_; }
      set {
        resultMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterToGGMResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterToGGMResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (ResultMsg != other.ResultMsg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (ResultMsg.Length != 0) hash ^= ResultMsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ResultMsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ResultMsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultMsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterToGGMResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.ResultMsg.Length != 0) {
        ResultMsg = other.ResultMsg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            ResultMsg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 18: {
            ResultMsg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExecuteGGCommandRequest : pb::IMessage<ExecuteGGCommandRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecuteGGCommandRequest> _parser = new pb::MessageParser<ExecuteGGCommandRequest>(() => new ExecuteGGCommandRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExecuteGGCommandRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandRequest(ExecuteGGCommandRequest other) : this() {
      command_ = other.command_;
      targetServerId_ = other.targetServerId_;
      timeStamp_ = other.timeStamp_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.GameServerInfoNode:
          GameServerInfoNode = other.GameServerInfoNode.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandRequest Clone() {
      return new ExecuteGGCommandRequest(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private global::HS.Protobuf.Common.GateCommand command_ = global::HS.Protobuf.Common.GateCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.GateCommand Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "targetServerId" field.</summary>
    public const int TargetServerIdFieldNumber = 2;
    private int targetServerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetServerId {
      get { return targetServerId_; }
      set {
        targetServerId_ = value;
      }
    }

    /// <summary>Field number for the "timeStamp" field.</summary>
    public const int TimeStampFieldNumber = 3;
    private long timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "gameServerInfoNode" field.</summary>
    public const int GameServerInfoNodeFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.ServerInfoNode GameServerInfoNode {
      get { return payloadCase_ == PayloadOneofCase.GameServerInfoNode ? (global::HS.Protobuf.Common.ServerInfoNode) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.GameServerInfoNode;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      GameServerInfoNode = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExecuteGGCommandRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExecuteGGCommandRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      if (TargetServerId != other.TargetServerId) return false;
      if (TimeStamp != other.TimeStamp) return false;
      if (!object.Equals(GameServerInfoNode, other.GameServerInfoNode)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Command != global::HS.Protobuf.Common.GateCommand.None) hash ^= Command.GetHashCode();
      if (TargetServerId != 0) hash ^= TargetServerId.GetHashCode();
      if (TimeStamp != 0L) hash ^= TimeStamp.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) hash ^= GameServerInfoNode.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (TargetServerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetServerId);
      }
      if (TimeStamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        output.WriteRawTag(34);
        output.WriteMessage(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (TargetServerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetServerId);
      }
      if (TimeStamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        output.WriteRawTag(34);
        output.WriteMessage(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (TargetServerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetServerId);
      }
      if (TimeStamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExecuteGGCommandRequest other) {
      if (other == null) {
        return;
      }
      if (other.Command != global::HS.Protobuf.Common.GateCommand.None) {
        Command = other.Command;
      }
      if (other.TargetServerId != 0) {
        TargetServerId = other.TargetServerId;
      }
      if (other.TimeStamp != 0L) {
        TimeStamp = other.TimeStamp;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.GameServerInfoNode:
          if (GameServerInfoNode == null) {
            GameServerInfoNode = new global::HS.Protobuf.Common.ServerInfoNode();
          }
          GameServerInfoNode.MergeFrom(other.GameServerInfoNode);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Command = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
          case 16: {
            TargetServerId = input.ReadInt32();
            break;
          }
          case 24: {
            TimeStamp = input.ReadInt64();
            break;
          }
          case 34: {
            global::HS.Protobuf.Common.ServerInfoNode subBuilder = new global::HS.Protobuf.Common.ServerInfoNode();
            if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
              subBuilder.MergeFrom(GameServerInfoNode);
            }
            input.ReadMessage(subBuilder);
            GameServerInfoNode = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Command = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
          case 16: {
            TargetServerId = input.ReadInt32();
            break;
          }
          case 24: {
            TimeStamp = input.ReadInt64();
            break;
          }
          case 34: {
            global::HS.Protobuf.Common.ServerInfoNode subBuilder = new global::HS.Protobuf.Common.ServerInfoNode();
            if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
              subBuilder.MergeFrom(GameServerInfoNode);
            }
            input.ReadMessage(subBuilder);
            GameServerInfoNode = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExecuteGGCommandResponse : pb::IMessage<ExecuteGGCommandResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecuteGGCommandResponse> _parser = new pb::MessageParser<ExecuteGGCommandResponse>(() => new ExecuteGGCommandResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExecuteGGCommandResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandResponse(ExecuteGGCommandResponse other) : this() {
      resultCode_ = other.resultCode_;
      errCommand_ = other.errCommand_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteGGCommandResponse Clone() {
      return new ExecuteGGCommandResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "errCommand" field.</summary>
    public const int ErrCommandFieldNumber = 2;
    private global::HS.Protobuf.Common.GateCommand errCommand_ = global::HS.Protobuf.Common.GateCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.GateCommand ErrCommand {
      get { return errCommand_; }
      set {
        errCommand_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExecuteGGCommandResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExecuteGGCommandResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (ErrCommand != other.ErrCommand) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) hash ^= ErrCommand.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCommand);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExecuteGGCommandResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        ErrCommand = other.ErrCommand;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 16: {
            ErrCommand = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 16: {
            ErrCommand = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExecuteSCommandRequest : pb::IMessage<ExecuteSCommandRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecuteSCommandRequest> _parser = new pb::MessageParser<ExecuteSCommandRequest>(() => new ExecuteSCommandRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExecuteSCommandRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandRequest(ExecuteSCommandRequest other) : this() {
      command_ = other.command_;
      targetServerId_ = other.targetServerId_;
      timeStamp_ = other.timeStamp_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.GameServerInfoNode:
          GameServerInfoNode = other.GameServerInfoNode.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandRequest Clone() {
      return new ExecuteSCommandRequest(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private global::HS.Protobuf.Common.GateCommand command_ = global::HS.Protobuf.Common.GateCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.GateCommand Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "targetServerId" field.</summary>
    public const int TargetServerIdFieldNumber = 2;
    private int targetServerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetServerId {
      get { return targetServerId_; }
      set {
        targetServerId_ = value;
      }
    }

    /// <summary>Field number for the "timeStamp" field.</summary>
    public const int TimeStampFieldNumber = 3;
    private long timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "gameServerInfoNode" field.</summary>
    public const int GameServerInfoNodeFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.ServerInfoNode GameServerInfoNode {
      get { return payloadCase_ == PayloadOneofCase.GameServerInfoNode ? (global::HS.Protobuf.Common.ServerInfoNode) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.GameServerInfoNode;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      GameServerInfoNode = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExecuteSCommandRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExecuteSCommandRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      if (TargetServerId != other.TargetServerId) return false;
      if (TimeStamp != other.TimeStamp) return false;
      if (!object.Equals(GameServerInfoNode, other.GameServerInfoNode)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Command != global::HS.Protobuf.Common.GateCommand.None) hash ^= Command.GetHashCode();
      if (TargetServerId != 0) hash ^= TargetServerId.GetHashCode();
      if (TimeStamp != 0L) hash ^= TimeStamp.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) hash ^= GameServerInfoNode.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (TargetServerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetServerId);
      }
      if (TimeStamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        output.WriteRawTag(34);
        output.WriteMessage(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (TargetServerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetServerId);
      }
      if (TimeStamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        output.WriteRawTag(34);
        output.WriteMessage(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Command != global::HS.Protobuf.Common.GateCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (TargetServerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetServerId);
      }
      if (TimeStamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeStamp);
      }
      if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameServerInfoNode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExecuteSCommandRequest other) {
      if (other == null) {
        return;
      }
      if (other.Command != global::HS.Protobuf.Common.GateCommand.None) {
        Command = other.Command;
      }
      if (other.TargetServerId != 0) {
        TargetServerId = other.TargetServerId;
      }
      if (other.TimeStamp != 0L) {
        TimeStamp = other.TimeStamp;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.GameServerInfoNode:
          if (GameServerInfoNode == null) {
            GameServerInfoNode = new global::HS.Protobuf.Common.ServerInfoNode();
          }
          GameServerInfoNode.MergeFrom(other.GameServerInfoNode);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Command = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
          case 16: {
            TargetServerId = input.ReadInt32();
            break;
          }
          case 24: {
            TimeStamp = input.ReadInt64();
            break;
          }
          case 34: {
            global::HS.Protobuf.Common.ServerInfoNode subBuilder = new global::HS.Protobuf.Common.ServerInfoNode();
            if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
              subBuilder.MergeFrom(GameServerInfoNode);
            }
            input.ReadMessage(subBuilder);
            GameServerInfoNode = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Command = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
          case 16: {
            TargetServerId = input.ReadInt32();
            break;
          }
          case 24: {
            TimeStamp = input.ReadInt64();
            break;
          }
          case 34: {
            global::HS.Protobuf.Common.ServerInfoNode subBuilder = new global::HS.Protobuf.Common.ServerInfoNode();
            if (payloadCase_ == PayloadOneofCase.GameServerInfoNode) {
              subBuilder.MergeFrom(GameServerInfoNode);
            }
            input.ReadMessage(subBuilder);
            GameServerInfoNode = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExecuteSCommandResponse : pb::IMessage<ExecuteSCommandResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecuteSCommandResponse> _parser = new pb::MessageParser<ExecuteSCommandResponse>(() => new ExecuteSCommandResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExecuteSCommandResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandResponse(ExecuteSCommandResponse other) : this() {
      resultCode_ = other.resultCode_;
      errCommand_ = other.errCommand_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecuteSCommandResponse Clone() {
      return new ExecuteSCommandResponse(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "errCommand" field.</summary>
    public const int ErrCommandFieldNumber = 2;
    private global::HS.Protobuf.Common.GateCommand errCommand_ = global::HS.Protobuf.Common.GateCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HS.Protobuf.Common.GateCommand ErrCommand {
      get { return errCommand_; }
      set {
        errCommand_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExecuteSCommandResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExecuteSCommandResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (ErrCommand != other.ErrCommand) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) hash ^= ErrCommand.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCommand);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExecuteSCommandResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.ErrCommand != global::HS.Protobuf.Common.GateCommand.None) {
        ErrCommand = other.ErrCommand;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 16: {
            ErrCommand = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 16: {
            ErrCommand = (global::HS.Protobuf.Common.GateCommand) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RegisterSessionToGGMRequest : pb::IMessage<RegisterSessionToGGMRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterSessionToGGMRequest> _parser = new pb::MessageParser<RegisterSessionToGGMRequest>(() => new RegisterSessionToGGMRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterSessionToGGMRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMRequest(RegisterSessionToGGMRequest other) : this() {
      taskId_ = other.taskId_;
      worldId_ = other.worldId_;
      sessionId_ = other.sessionId_;
      uId_ = other.uId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMRequest Clone() {
      return new RegisterSessionToGGMRequest(this);
    }

    /// <summary>Field number for the "taskId" field.</summary>
    public const int TaskIdFieldNumber = 1;
    private int taskId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    /// <summary>Field number for the "worldId" field.</summary>
    public const int WorldIdFieldNumber = 2;
    private int worldId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "sessionId" field.</summary>
    public const int SessionIdFieldNumber = 3;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uId" field.</summary>
    public const int UIdFieldNumber = 4;
    private string uId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UId {
      get { return uId_; }
      set {
        uId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterSessionToGGMRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterSessionToGGMRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskId != other.TaskId) return false;
      if (WorldId != other.WorldId) return false;
      if (SessionId != other.SessionId) return false;
      if (UId != other.UId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskId != 0) hash ^= TaskId.GetHashCode();
      if (WorldId != 0) hash ^= WorldId.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (UId.Length != 0) hash ^= UId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (WorldId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WorldId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (UId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (WorldId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WorldId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (UId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      if (WorldId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WorldId);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (UId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterSessionToGGMRequest other) {
      if (other == null) {
        return;
      }
      if (other.TaskId != 0) {
        TaskId = other.TaskId;
      }
      if (other.WorldId != 0) {
        WorldId = other.WorldId;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.UId.Length != 0) {
        UId = other.UId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            WorldId = input.ReadInt32();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 34: {
            UId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            WorldId = input.ReadInt32();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 34: {
            UId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RegisterSessionToGGMResponse : pb::IMessage<RegisterSessionToGGMResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterSessionToGGMResponse> _parser = new pb::MessageParser<RegisterSessionToGGMResponse>(() => new RegisterSessionToGGMResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterSessionToGGMResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HS.Protobuf.GameGateMgr.GameGateMgrReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMResponse(RegisterSessionToGGMResponse other) : this() {
      taskId_ = other.taskId_;
      resultCode_ = other.resultCode_;
      resultMsg_ = other.resultMsg_;
      gameGateInfos_ = other.gameGateInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterSessionToGGMResponse Clone() {
      return new RegisterSessionToGGMResponse(this);
    }

    /// <summary>Field number for the "taskId" field.</summary>
    public const int TaskIdFieldNumber = 1;
    private int taskId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 2;
    private int resultCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "resultMsg" field.</summary>
    public const int ResultMsgFieldNumber = 3;
    private string resultMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResultMsg {
      get { return resultMsg_; }
      set {
        resultMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gameGateInfos" field.</summary>
    public const int GameGateInfosFieldNumber = 4;
    private static readonly pb::FieldCodec<global::HS.Protobuf.Common.ServerInfoNode> _repeated_gameGateInfos_codec
        = pb::FieldCodec.ForMessage(34, global::HS.Protobuf.Common.ServerInfoNode.Parser);
    private readonly pbc::RepeatedField<global::HS.Protobuf.Common.ServerInfoNode> gameGateInfos_ = new pbc::RepeatedField<global::HS.Protobuf.Common.ServerInfoNode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HS.Protobuf.Common.ServerInfoNode> GameGateInfos {
      get { return gameGateInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterSessionToGGMResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterSessionToGGMResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskId != other.TaskId) return false;
      if (ResultCode != other.ResultCode) return false;
      if (ResultMsg != other.ResultMsg) return false;
      if(!gameGateInfos_.Equals(other.gameGateInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskId != 0) hash ^= TaskId.GetHashCode();
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (ResultMsg.Length != 0) hash ^= ResultMsg.GetHashCode();
      hash ^= gameGateInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (ResultCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ResultMsg);
      }
      gameGateInfos_.WriteTo(output, _repeated_gameGateInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (ResultCode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ResultMsg);
      }
      gameGateInfos_.WriteTo(ref output, _repeated_gameGateInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultCode);
      }
      if (ResultMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultMsg);
      }
      size += gameGateInfos_.CalculateSize(_repeated_gameGateInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterSessionToGGMResponse other) {
      if (other == null) {
        return;
      }
      if (other.TaskId != 0) {
        TaskId = other.TaskId;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.ResultMsg.Length != 0) {
        ResultMsg = other.ResultMsg;
      }
      gameGateInfos_.Add(other.gameGateInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 26: {
            ResultMsg = input.ReadString();
            break;
          }
          case 34: {
            gameGateInfos_.AddEntriesFrom(input, _repeated_gameGateInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            ResultCode = input.ReadInt32();
            break;
          }
          case 26: {
            ResultMsg = input.ReadString();
            break;
          }
          case 34: {
            gameGateInfos_.AddEntriesFrom(ref input, _repeated_gameGateInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
